# Generated by Django 6.0.2 on 2026-02-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('topic', models.CharField(max_length=255)),
                ('time_spent', models.DecimalField(decimal_places=2, help_text='Hours spent', max_digits=4)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Incomplete', 'Incomplete')], default='Completed', max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='goals.goal')),
            ],
        ),
    ]
