# Generated by Django 6.0.2 on 2026-02-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_target', models.PositiveIntegerField(help_text='Target hours per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
